### PR TITLE
fix: Function components cannot be given refs

### LINKED ISSUE #29: Bug: Function components cannot be given refs
### What happened 🆘

When you run the app locally, you get the following error

Cursor

### To Reproduce 🔂

Just run the app locally and observe the error in the console

### PR DESCRIPTION
**Pull request by karelianpie**
Fixes https://github.com/yearn/macarena-finance/issues/29

Wraps the function component in `a` tag and `passRef` to the `Link` component

### CODE REVIEW

File: components/common/Card.tsx [hunk 1]
```diff
@@ -132,14 +132,14 @@ function	CardWithTabs(props: TCardWithTabs): ReactElement {
 }
 
 function	CardBase(props: TCard): ReactElement {
-	const {children, onClick, padding = 'regular', variant = 'surface', ...rest} = props;
+	const {children, onClick, padding = 'regular', variant = 'surface', className, ...rest} = props;
```
Comment (karelianpie) [inline components/common/Card.tsx:135]: This change wasn't really related to the PR, but as we're spreading the remaining props, we will be spreading the `className` once again, so invalidating the already set className value

File: pages/index.tsx [hunk 2]
```diff
@@ -19,63 +19,65 @@ function	VaultCard({currentVault}: {currentVault: TVault}): ReactElement {
...
-							variants={slashMotion}
-							className={'macarena--vaultCard flex flex-col items-start justify-between p-6 pb-4'}>
-							<div className={'flex w-full flex-row items-start justify-between'}>
-								<div className={'min-h-[32px] min-w-[32px] md:min-h-[80px] md:min-w-[80px]'}>
-									<Image
-										src={currentVault.token.icon}
-										width={80}
-										height={80} />
+			<Link href={`/vault/${currentVault.address}`} passHref>
+				<a>
```
Comment (karelianpie) [inline pages/index.tsx:23]: Looks like a lot has changed, but literally was just wrapping this in an `a` tag :)

**Review by Majorfi — APPROVED** [review]
